version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/bibo-app
    docker:
      - image: circleci/node:10-browsers
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          key: bibo-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: bibo-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm install
      - run: npm run test
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/bibo-app
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: npm run firebase-deploy -- --token=$FIREBASE_TOKEN
